# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1519)
$foreground = rgb(FDF1F0)
$color0 = rgb(413C41)
$color1 = rgb(1C0A1B)
$color2 = rgb(4D2060)
$color3 = rgb(4643A8)
$color4 = rgb(834255)
$color5 = rgb(AA7BB2)
$color6 = rgb(BCA2A0)
$color7 = rgb(F4E3E2)
$color8 = rgb(AB9F9E)
$color9 = rgb(250E24)
$color10 = rgb(662A80)
$color11 = rgb(5D5AE0)
$color12 = rgb(AF5871)
$color13 = rgb(E2A4ED)
$color14 = rgb(FAD8D5)
$color15 = rgb(F4E3E2)
