#!/usr/bin/env bash
# AUTO-GENERATED by save-session.sh -- re-run that script to update.
# Restores the Hyprland window layout captured at save time.
# Each app is launched onto its workspace; the apps themselves reopen
# their last tabs/vault/project. A short delay lets each map before the
# next launches so the tiling order is preserved.
set -u

DELAY="${SESSION_RESTORE_DELAY:-1.2}"
# This Hyprland uses the Lua config, so `hyprctl dispatch` is evaluated as
# Lua -- exec must go through hl.dsp.exec_cmd(...), NOT `dispatch exec`.
# Apps are launched via `uwsm app --` (matches the keybinds) so they get a
# proper systemd scope/environment; override with SESSION_LAUNCH_PREFIX.
PREFIX="${SESSION_LAUNCH_PREFIX-uwsm app -- }"

launch() {
  local ws="$1"; shift
  echo "  ws $ws: $*"
  hyprctl dispatch "hl.dsp.exec_cmd(\"[workspace $ws silent] ${PREFIX}$*\")" >/dev/null
  sleep "$DELAY"
}

launch 1 google-chrome-stable --restore-last-session    # google-chrome
launch 1 kitty    # kitty
launch 2 github-desktop    # GitHub Desktop
launch 2 obsidian    # obsidian
launch 3 zeditor    # dev.zed.Zed

echo "Done. Restored 5 window(s). Note: terminal programs (e.g. the"
echo "claude session) are not auto-restarted -- reopen those manually."
notify-send -a session-restore "Session restored" "Relaunched 5 apps. Terminal programs reopen empty -- restart those manually." || true
