#!/usr/bin/env python3
"""
Save the current Hyprland window layout so it can be restored after a reboot
(e.g. after booting into Windows to game and coming back).

Writes two files next to this script:
  - session-snapshot.json   full `hyprctl clients` dump (reference / debugging)
  - restore-session.sh      generated script that relaunches everything

Re-run this any time your layout changes and you want to update the saved state.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, "session-snapshot.json")
RESTORE = os.path.join(HERE, "restore-session.sh")

# class (from `hyprctl clients`) -> command used to launch it.
# "single" apps manage their own windows on relaunch (they reopen the last
# session/vault/project), so we launch them once no matter how many windows
# they had. "multi" apps (terminals) get one launch per window.
APP_MAP = {
    # --restore-last-session reopens the previous windows/tabs. (Editing the
    # session.restore_on_startup pref instead does NOT work: it's an HMAC-
    # protected pref and Chrome ignores out-of-band edits.)
    "google-chrome":   {"cmd": "google-chrome-stable --restore-last-session", "single": True},
    "obsidian":        {"cmd": "obsidian",             "single": True},
    "GitHub Desktop":  {"cmd": "github-desktop",       "single": True},
    "dev.zed.Zed":     {"cmd": "zeditor",              "single": True},
    "kitty":           {"cmd": "kitty",                "single": False},
}


def launch_cmd(cls, pid):
    if cls in APP_MAP:
        return APP_MAP[cls]
    # Fallback: use argv[0] basename from /proc, launched once per window.
    try:
        with open(f"/proc/{pid}/cmdline", "rb") as f:
            argv0 = f.read().split(b"\x00")[0].decode()
        return {"cmd": os.path.basename(argv0), "single": False}
    except Exception:
        return None


def main():
    clients = json.loads(subprocess.check_output(["hyprctl", "clients", "-j"]))
    with open(SNAPSHOT, "w") as f:
        json.dump(clients, f, indent=2)

    # Build the list of launches: (workspace_id, command). Preserve on-screen
    # order (left-to-right, top-to-bottom) so the dwindle layout is reproduced.
    clients.sort(key=lambda c: (c["workspace"]["id"], c["at"][0], c["at"][1]))

    launches = []
    seen_single = set()
    skipped = []
    for c in clients:
        cls = c["class"]
        ws = c["workspace"]["id"]
        if ws < 1:  # special/scratchpad workspaces
            continue
        info = launch_cmd(cls, c["pid"])
        if not info:
            skipped.append(cls)
            continue
        if info["single"]:
            if cls in seen_single:
                continue
            seen_single.add(cls)
        launches.append((ws, info["cmd"], cls))

    lines = [
        "#!/usr/bin/env bash",
        "# AUTO-GENERATED by save-session.sh -- re-run that script to update.",
        "# Restores the Hyprland window layout captured at save time.",
        "# Each app is launched onto its workspace; the apps themselves reopen",
        "# their last tabs/vault/project. A short delay lets each map before the",
        "# next launches so the tiling order is preserved.",
        "set -u",
        "",
        'DELAY="${SESSION_RESTORE_DELAY:-1.2}"',
        "# This Hyprland uses the Lua config, so `hyprctl dispatch` is evaluated as",
        "# Lua -- exec must go through hl.dsp.exec_cmd(...), NOT `dispatch exec`.",
        "# Apps are launched via `uwsm app --` (matches the keybinds) so they get a",
        "# proper systemd scope/environment; override with SESSION_LAUNCH_PREFIX.",
        'PREFIX="${SESSION_LAUNCH_PREFIX-uwsm app -- }"',
        "",
        "launch() {",
        "  local ws=\"$1\"; shift",
        '  echo "  ws $ws: $*"',
        "  hyprctl dispatch \"hl.dsp.exec_cmd(\\\"[workspace $ws silent] ${PREFIX}$*\\\")\" >/dev/null",
        '  sleep "$DELAY"',
        "}",
        "",
    ]
    for ws, cmd, cls in launches:
        lines.append(f"launch {ws} {cmd}    # {cls}")
    lines += [
        "",
        'echo "Done. Restored %d window(s). Note: terminal programs (e.g. the"' % len(launches),
        'echo "claude session) are not auto-restarted -- reopen those manually."',
        'notify-send -a session-restore "Session restored" '
        '"Relaunched %d apps. Terminal programs reopen empty -- restart those manually." || true'
        % len(launches),
        "",
    ]

    with open(RESTORE, "w") as f:
        f.write("\n".join(lines))
    os.chmod(RESTORE, 0o755)

    nws = len(set(w for w, _, _ in launches))
    print(f"Saved snapshot:  {SNAPSHOT}")
    print(f"Wrote restore:   {RESTORE}")
    print(f"Captured {len(launches)} launch(es) across {nws} workspace(s).")
    msg = f"{len(launches)} apps across {nws} workspaces"
    if skipped:
        print(f"WARNING: no launch command known for: {sorted(set(skipped))}",
              file=sys.stderr)
        msg += f"\nUnknown: {', '.join(sorted(set(skipped)))}"
    subprocess.run(["notify-send", "-a", "session-save",
                    "Session saved", msg], check=False)


if __name__ == "__main__":
    main()
