# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDF1F0
background         #1A1519
cursor             #B28EB8

active_tab_foreground     #1A1519
active_tab_background     #FDF1F0
inactive_tab_foreground   #FDF1F0
inactive_tab_background   #1A1519

active_border_color   #FDF1F0
inactive_border_color #1A1519
bell_border_color     #1C0A1B

color0      #413C41
color1		#1C0A1B
color2		#4D2060
color3		#4643A8
color4		#834255
color5		#AA7BB2
color6		#BCA2A0
color7		#F4E3E2
color8		#AB9F9E
color9		#250E24
color10		#662A80
color11		#5D5AE0
color12		#AF5871
color13		#E2A4ED
color14		#FAD8D5
color15		#F4E3E2
